import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {"Hello! It's Alan."}
          {/* <Link href="/FlipCards">WELCOME!</Link>  */}
        </h1>
        <h5>Email: b98705028@gmail.com</h5>
      </main>
    </div>
  )
}
